name: genesys-mod-plotter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - dash
  - pyyaml
  - plotly
  - pip
  - pip:
    - kaleido==0.1.0post1
    - nbformat
    - openpyxl